### ISSUE TITLE
Layers merge missing

### ISSUE THREAD

**Issue by TheFallOutGuy** [ptedeschi/NFT.net#7]
Heyho,

I really like the idea for this program.
Maybe I'm wrong - and try to use wrongly the app.
I have 2 layers -> 1-background and 2-frames. I've generated the files - ok. But at the end I just get back the original frames files with white background in the output/images.

I use .png type and setted the same scales for the pics also - I tried out, if the scale is not okay than got exception for that.
No subfolders used in the background or frames.
In the metadata the trait_type for background it looks okay and proper.

So where should I search for the problem? I use the newest release for this project and win10.

Thanks.

BR,
TheFallOutGuy

**Comment by ptedeschi** [comment]
Hello @TheFallOutGuy!
Glad you liked the project. Don't forget to star it.

We can try 3 things...

1. In this repository I have a [sample folder](https://github.com/ptedeschi/NFT.net/tree/master/sample/layers), Try to generate using these files as your source files. Hope it works normally and we can prove that the tool is working fine in your environment
2. Invert your folders order... Rename your background as `2-background` and your frame as `1-frames`. Check what happens...
3. If it doesn't work, could you send me some examples of the files you are using? So I can try to diagnose the problem here. If you agree, send me the files to ilpinguinonft@gmail.com.

Cheers!

**Comment by ptedeschi** [comment]
Hi @TheFallOutGuy!
Please let me know how it ended.
Cheers!

**Comment by ptedeschi** [comment]
Closing the issue because the reporter did not provide more information after the suggested solution.
If the error persists, please open a new issue!
Cheers!
